### ISSUE TITLE
Cant find it through the wordpress plugins browser :(

### ISSUE THREAD

**Issue by doza62** [brettkrueger/multisite-rest-api#5]
I have not tested this plugin yet, but I've been searching this for months dreading having to do this myself. It fits perfectly my needs. But I understand now why it took so long to find it... It does not show up while searching for it!
![image](https://user-images.githubusercontent.com/14064394/100255851-6e3bcc80-2f1a-11eb-8eba-21169c0892a5.png)

Only while typing this exactly:
![image](https://user-images.githubusercontent.com/14064394/100255953-87447d80-2f1a-11eb-8478-b0c1a5e720e2.png)

I will make sure to leave a review so this can bee seen by more people so this project does not dies :(

Thank you for developing this!

**Comment by brettkrueger** [comment]
Howdy @R0dri! I realize this is several years old at this point, but just wanted to circle back to confirm that this is showing in search results now for me (page 3 specifically). I'll go ahead and mark this as closed for now, but if you notice any other issues, do let me know!
![image](https://github.com/brettkrueger/multisite-rest-api/assets/4055974/433cdabb-5c47-4ecb-9b54-1c7d9e2ab1f6)
